### PR TITLE
Update readme.md

### LINKED ISSUE #1: Add More Docs
Most of the endpoints that are newly added  are not documented. Needs more concise documentation. One can obtain information by referring to the code and inline comments in /api/routes.js file. Thanks

### PR DESCRIPTION
**Pull request by cyberdad68**
Updating Endpoints in Readme.md File

Closes #1

### CODE REVIEW

**Review by alanJames00 — APPROVED** [review]
LGTM!

**Comment by alanJames00** [comment]
@cyberdad68 Thank you for your contributions. Really appreciate it. 
If you have any doubts regarding your hacktoberfest related stuff, just ask me.
Thanks man.

**Comment by cyberdad68** [comment]
@alanJames00 Could you please add Hacktoberfest Accepted Label on this Repo.

**Comment by alanJames00** [comment]
Added 👍️.

BTW, did you receive any email from hacktoberfest saying that your PR is under review ??

**Comment by cyberdad68** [comment]
> Added 👍️.
> 
> BTW, did you receive any email from hacktoberfest saying that your PR is under review ??

Yes,it is under review.

**Comment by alanJames00** [comment]
@cyberdad68 Nothing to Worry, it will be approved by hacktoberfest after 7 days. By that time, make sure to do some other contributions since we're currently right after the middle of october.
Happy Hacking 👨‍💻

**Pull request merged**
